// List of subreddits to scrape

exports.array = [
	"offmychest",
	"ripplingalcoholism",
	"disorder",
	"MenGetRapedToo",
	"rapecounseling",
	"addiction",
	"AlmostHomeless",
	"Homeless",
	"MakeNewFriendsHere",
	"MakeMeFeelBetter",
	"Assistance",
	"ADHD",
	"Advice",
//	"needadvice",
	"alcoholicsanonymous",
	"alcoholism",
	"Anger",
	"Anxiety",
	"Anxietyhelp",
	"BodyAcceptance",
	"depression",
	"ForeverAlone",
	"getting_over_it",
	"ptsd",
	"whatsbotheringyou",
	"survivorsofabuse",
	"SuicideWatch",
	"StopSelfHarm",
	"rape",
	"reasonstolive",
	"sad",
	"stopdrinking",
	"selfharm",
	"selfhelp",
	"Needafriend",
	"itgetsbetter",
	"mentalillness",
	"mentalhealth"
]