// List of subreddits to scrape

exports.array = [
	"disorder",
	"MenGetRapedToo",
	"rapecounseling",
	"addiction",
	"AlmostHomeless",
	"Homeless",
	"MakeNewFriendsHere",
	"MakeMeFeelBetter",
	"Assistance",
	"Advice",
	"alcoholicsanonymous",
	"alcoholism",
	"Anger",
	"Anxietyhelp",
	"anxietysupporters",
	"Phobia",
	"tOCD",
	"whatsbotheringyou",
	"survivorsofabuse",
	"StopSelfHarm",
	"rape",
	"reasonstolive",
	"sad",
	"stopdrinking",
	"helpmecope",
	"selfhelp",
	"Needafriend",
	"itgetsbetter",
	"mentalillness",
	"mentalhealth"
]